# -*- coding: utf-8 -*-
"""Recaman Sequence Number Generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f6K-sbHl5ieL4f4p4s-sQIZnEZuDvcp6
"""

n = a = 0
lasta = None
n_iterations = 50
final_number = 0


def concat(a, b):
    return int(f"{a}{b}")

while n < n_iterations:
    lasta = a
    b = a - n
    if b > 0 and b not in seen:
        a = b
    else:
        a = a + n
    final_number = concat(final_number, a)
    n += 1

print(final_number)